# Podfile for Omega Push Notifications Test App

platform :ios, '14.0'
use_frameworks!

target 'OmegaPushTest' do
  # Firebase Cloud Messaging
  pod 'Firebase/Messaging'
  
  # Firebase Core (required)
  pod 'Firebase/Analytics'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
